pipeline {
    agent { dockerfile {
          dir 'jenkins/model'
        }
    }
    stages {
		stage('clean up from previous run') {
		    steps {
			    sh label: 'remove an old file (force in case does not exist)', script: 'rm -f run_models.sh'
		        sh label: 'remove an old dir (force in case does not exist)', script: 'rm -rf ss_bin'
				sh label: 'remove old files (force in case does not exist)', script: 'rm -f models.zip'
			    sh label: 'remove old files (force in case does not exist)', script: 'rm -f ss'
				sh label: 'remove old files (force in case does not exist)', script: 'rm -f models/ss'
				sh label: 'remove old dir (force in case does not exist)', script: 'rm -rf model_runs'
				// sh label: 'view folders/files', script: 'ls .'
				sh label: 'view model files', script: 'ls models/Simple'
			}
		}
	    stage('move shell script') {
		    steps{
			    sh label: 'copy over new version', script: 'cp jenkins/model/run_models.sh run_models.sh'
				sh label: 'Make executable', script: 'chmod a+x run_models.sh'  
			}
		}
        stage('Copy ss.gz artifact from previous stage') {
            steps {
              copyArtifacts filter: 'ss.gz', fingerprintArtifacts: true, projectName: 'stock-synthesis-build', selector: lastSuccessful()
			}
        }
	    stage('copy model files to a new directory') {
		    steps{
			    sh label: 'Move ss executable', script: 'mv models model_runs'
			}
		}
        stage('Unpack ss.gz artifact') {
            steps {
                sh label: 'Unzip ss', script: 'gunzip ss.gz'
                sh label: 'Make ss executable', script: 'chmod a+rwx ss'
				sh label: 'make ss executable folder', script: 'mkdir ss_bin'
				sh label: 'Move ss executable', script: 'mv ss ss_bin/ss'
                // sh label: 'Get dir listing', script: 'ls -alh *'
            }
        }
		stage('Run ss on models') {
            steps {   
				sh label: 'Put SS in path and run models', script: './run_models.sh'
            }
        }
    }
    post {
	    always {
                sh label: 'Zip models folder', script: 'zip -r models.zip model_runs'
                archiveArtifacts 'models.zip'
		}
        failure {
            mail bcc: '', body: 'Stock Synthesis build failed.', cc: '', from: '', replyTo: '', subject: 'stock-synthesis-model: Jenkins Build Failure', to: 'kathryn.doering@noaa.gov richard.methot@noaa.gov ian.taylor@noaa.gov'
        }
        changed {
            script {
                if (currentBuild.currentResult == 'SUCCESS') { // Other values: SUCCESS, UNSTABLE
                    // Send an email only if the build status has changed from red to green
                   mail bcc: '', body: 'Stock Synthesis build now passing!', cc: '', from: '', replyTo: '', subject: 'stock-synthesis-model: Jenkins Build Passing Again', to: 'kathryn.doering@noaa.gov richard.methot@noaa.gov ian.taylor@noaa.gov'
                }
            }
        }
    }
}